Dataframe important Methods:

In [ ]:
import pandas as pd
import numpy as np

More important Dataframe Function:
                        
                               """  value_counts()
                                    sort_values()
                                    rank()
                                    sort index()
                                    set index()
                                    rename index() -> rename
                                    reset index()
                                    unique() & nunique()
                                    isnull()/notnull()/hasnans()
                                    dropna()
                                    fillna()
                                    drop_duplicates()
                                    drop()
                                    apply()
                                    isin()
                                    corr()
                                    nlargest() -> nsmallest()
                                    insert()
                                    copy()"""

In [ ]:
"value_counts(): ---> applicable both on series and dataframe ===> more important in case of series"
marks = pd.DataFrame([
    [100,80,10],
    [90,70,8],
    [80,70,6],
    [120,100,11],
    [120,100,11]
],columns=["IQ","Marks","Package"])

"it will return the number rows repeat"
marks.value_counts()

In [ ]:
ipl = pd.read_csv("ipl-matches.csv")
vk = pd.read_csv("kohli_ipl.csv")
movies = pd.read_csv("movies.csv")
diabetes = pd.read_csv("diabetes.csv")
subs = pd.read_csv("subs.csv")
batsman_runs = pd.read_csv("batsman_runs_ipl.csv")

In [ ]:
ipl["MatchNumber"]

In [ ]:
"find which player has own potm -> in finals and qualifiers"
ipl[~ipl["MatchNumber"].str.isdigit()]["Player_of_Match"].value_counts()

In [ ]:
ipl["TossDecision"].value_counts().plot(kind="pie")

In [ ]:
ipl

In [ ]:
(ipl["Team1"].value_counts() + ipl["Team2"].value_counts()).sort_values(ascending=False)

In [ ]:
movies.head(4)

In [ ]:
"sort_values(): through this we can sort the dataframe by any column through ascending or descending order"
movies.sort_values("title_x",ascending=False)

In [ ]:
students = pd.DataFrame(
    {
        'name':['nitish','ankit','rupesh',np.nan,'mrityunjay',np.nan,'rishabh',np.nan,'aditya',np.nan],
        'college':['bit','iit','vit',np.nan,np.nan,'vlsi','ssit',np.nan,np.nan,'git'],
        'branch':['eee','it','cse',np.nan,'me','ce','civ','cse','bio',np.nan],
        'cgpa':[6.66,8.25,6.41,np.nan,5.6,9.0,7.4,10,7.4,np.nan],
        'package':[4,5,6,np.nan,6,7,8,9,np.nan,np.nan]
    }
)

In [ ]:
"Sorting on the bases of one column and througn na_postion we can tell it that nan value where to lie and inplace=True making changes permanent"
students.sort_values("name",na_position='first',ascending=False,inplace=True)

In [ ]:
students

In [ ]:
"Sorting on the bases of multiple columns:"
movies.head(2)

In [ ]:
movies.sort_values(["year_of_release","title_x"])

In [ ]:
movies.sort_values(["year_of_release","title_x"],ascending=[True,False])

In [ ]:
"""What we have learn until now:
series sorting
dataframe sorting
sorting dataframe on the bases of one column
sorting dataframe on the bases of multiple columns
how to perform permanent changes to dataframe.
how to internal sorting in the dataframe.
"""

In [ ]:
"rank(): it is a utality method. it may helps us in many scenarios.(this function only works with series and not works on dataframe.)"
batsman_runs

In [ ]:
batsman_runs["batting_rank"] = batsman_runs["batsman_run"].rank(ascending=False)
batsman_runs.sort_values("batting_rank",inplace=True)

In [ ]:
"sort_index(): the function works both on series and dataframe."
marks = {
    "Maths" : 67,
    "English": 57,
    "Science": 89,
    "Hindi": 100,
    "Hindi" : 100
}

marks_series = pd.Series(marks)
marks_series

In [ ]:
marks_series.sort_index(ascending=False) # Z - A
marks_series.sort_index() # A-Z by defualt

In [ ]:
movies.sort_index(ascending=False) # descending order sorting
movies.sort_index()

In [ ]:
"set_index(): only use on dataframe. inplace"
batsman_runs.sort_values("batter",inplace=True)
batsman_runs

In [ ]:
batsman_runs.set_index("batter",inplace=True)

In [ ]:
batsman_runs

In [ ]:
methods = """                        sort_values()
                                    rank()
                                    sort index()
                                    set index()
                                    rename index() -> rename
                                    reset index()
                                    unique() & nunique()
                                    isnull()/notnull()/hasnans()
                                    dropna()
                                    fillna()
                                    drop_duplicates()
                                    drop()
                                    apply()
                                    isin()
                                    corr()
                                    nlargest() -> nsmallest()
                                    insert()
                                    copy()"""

print(methods)

In [ ]:
"reset_index(): series + dataframe : it is totally opposite of the set_index() which set index."
batsman_runs.reset_index()

In [ ]:
batsman_runs

In [ ]:
batsman_runs.reset_index().set_index("batting_rank")

In [ ]:
marks_series.reset_index()
type(marks_series.reset_index())

In [ ]:
"rename(): dataframe only:"
movies.set_index("title_x",inplace=True)
movies

In [ ]:
movies.rename(columns={"poster_path":"link","imdb_id":"imdb"},inplace=True)
movies

In [ ]:
"what if we have to make changes in the index then instead of column={} we will write index={}:"
movies.rename(index={"Uri: The Surgical Strike": "URI","Battalion 609":"Battalion"},inplace=True)
movies

In [ ]:
"unique(): series only"
df = pd.Series([1,2,4,4,3,2,3,np.nan,np.nan])
df.unique()

In [ ]:
ipl

In [ ]:
"this function give the unique values present in the series."
ipl["Season"].unique()

In [ ]:
"nunique(): series + dataframe : this function gives us the number of unique values. but does not count the np.nan."
print(len(df.unique()))
print(df.nunique())
ipl["Season"].nunique()

Working with Missing values:

                       1) isnull() or isna() --> series + dataframe
                       2) notnull() --> series + dataframe
                       3) hasnans() --> series + dataframe

In [ ]:
students

In [ ]:
students["name"].isna()
students["name"].isnull()

In [ ]:
"these function are both same and isnull() is basically the alias of isna()."
students.isna()
students.isnull()

In [ ]:
"both are same okay but notnull is alias of notna()"
students["name"].notnull()
students["name"].notna()

In [ ]:
"Basically (isnull() and notnull()) or (isna() and notna()) both are complementry of each other"

In [ ]:
"hasnans: series: (attribute)  it tell us Is there any missing value or not"
students["name"].hasnans

In [ ]:
students

Dealing with Missing values:
                           
                           1) dropna() (series + dataframe) ---> Remove the missing values
                           2) fillna()  (series + dataframe) ---> fill the missing value with a desired value.

In [ ]:
students

In [ ]:
"On series:"
students["name"].dropna()

In [ ]:
students

In [ ]:
students.dropna() # it remove all rows in which there is least one missing values. (due to a hiden paraemter how="any" note: but we can override this behivour)

In [ ]:
students.dropna(how="all") # now it will remove if row contains all missing values.

In [ ]:
"we can drop values on the bases of column: if there is any values missing in the column then remove that particular row only"
students.dropna(subset=["name"])

In [ ]:
"we can also do on the basis of two columns. For permanent changes we will add inplace=True."
students.dropna(subset=["name","college"])
# students.dropna(subset=("name","college"))

In [ ]:
students

In [ ]:
students["name"].fillna("unkown")

In [ ]:
students.fillna("unkown") # but fill should be done on the bases of column by column.
students.fillna(0)

In [ ]:
students

In [ ]:
students["package"].fillna(round(students["package"].mean()))

In [ ]:
"""we can fill the missing values through forword and backword in which the missing value is fill through first value from and in backword fill the missing "
values is fill through value in its back."""
# students["name"].fillna(method="ffill")  <---- this method is now depreicated
students["name"].ffill()

In [ ]:
students["name"].bfill()

In [ ]:
"dropduplicates(): this function drops the duplicates in the dataframe + seies"
marks_series

In [ ]:
marks

In [ ]:
marks_series.duplicated().sum()
marks

In [ ]:
marks.drop_duplicates()

In [ ]:
marks.drop_duplicates(keep="last") # keep the first occurance

In [ ]:
marks.drop_duplicates(keep="first")

In [ ]:
"drop(): series + dataframe"
temp = pd.Series([1,20,64,93,49,24,29,1,20])
temp.drop([8,0],inplace=True)
temp

In [ ]:
students.drop(columns=["cgpa","branch"]) # we can specify the column.

In [ ]:
"similarliy we can drop the any row by specifiying it index like this."
students.drop(index=[8,3])
students.drop(index=[4,5,1,6])

In [ ]:
students.set_index("name").drop(index=["nitish","rishabh"])

apply(): very important function.

In [ ]:
"when we are applying the apply() function in a series then we are actully passing a row and in case of dataframe we are passing a column to apply() ok."
points_df = pd.DataFrame(
    {
        '1st point':[(3,4),(-6,5),(0,0),(-10,1),(4,5)],
        '2nd point':[(-3,4),(0,0),(2,2),(10,10),(1,1)]
    }
)

points_df

In [ ]:
temp = pd.Series([10,20,30,40,50])
def sigmoid(value):
    return 1/1 + np.exp(-value)

temp.apply(sigmoid)

In [131]:
points_df

  1st point 2nd point
0    (3, 4)   (-3, 4)
1   (-6, 5)    (0, 0)
2    (0, 0)    (2, 2)
3  (-10, 1)  (10, 10)
4    (4, 5)    (1, 1)

In [141]:
def euclidean_distance(row):
    p_A, p_B = row["1st point"], row["2nd point"]
    return ((p_A[0] - p_B[0]) **2 + (p_A[1] - p_B[1]) **2) ** 0.5

In [143]:
points_df["distance"] = points_df.apply(euclidean_distance,axis=1)

In [144]:
points_df

  1st point 2nd point   distance
0    (3, 4)   (-3, 4)   6.000000
1   (-6, 5)    (0, 0)   7.810250
2    (0, 0)    (2, 2)   2.828427
3  (-10, 1)  (10, 10)  21.931712
4    (4, 5)    (1, 1)   5.000000