In [ ]:
import pandas as pd
import numpy as np

Creating Dataframe:(combination of series)

                                      1) From list
                                      2) From Dict
                                      3) Using read_csv()

In [ ]:
number =  [[1,2,3],[4,5,6],[7,8,9]]
df = pd.DataFrame(number)
df

In [77]:
student_data = [[100,80,10],
                [120,100,14],
                [90,70,5],
                [70,60,4],
                [70,60,4]]
data  = pd.DataFrame(student_data,columns=["IQ","Marks","package"])
data

    IQ  Marks  package
0  100     80       10
1  120    100       14
2   90     70        5
3   70     60        4
4   70     60        4

In [ ]:
"using dictionary:"
student_data = {"student_IQ" : [100,120,90,70],
                "Marks": [90,100,70,60],
                "Package":[10,14,5,4]}
students = pd.DataFrame(student_data)
students

In [ ]:
"using read_csv"

movies = pd.read_csv("movies.csv")
ipl = pd.read_csv("ipl-matches.csv")
movies
ipl

DataFrame attributes:

                 1) shape
                 2) dtypes
                 3) index
                 4) columns
                 5) values

In [ ]:
movies.shape

In [ ]:
ipl.shape

In [ ]:
"For dataframe it return a series with column name is a index and datatype as value."
movies.dtypes

In [ ]:
ipl.dtypes

In [ ]:
ipl.dtypes

In [ ]:
movies.index

In [ ]:
ipl.index

In [ ]:
students.index

In [ ]:
data.index

In [ ]:
data.columns

In [ ]:
ipl.index

In [ ]:
ipl.columns  # give all columns name in a list

In [ ]:
movies.columns

In [ ]:
data.columns

In [ ]:
data.values

In [ ]:
ipl.values

Dataframe Method:
    
                1) head()
                2) tails()
                3) info()
                4) describe()
                5) isnull()
                6) sample()
                7) duplicated()
                8) rename()

In [ ]:
movies.head(5)

In [ ]:
ipl.head(5)

In [ ]:
movies.tail(5)

In [ ]:
ipl.tail(5)

In [ ]:
"sample(): take one row randomly"
movies.sample()

In [ ]:
"getting multiple rows through sample"
movies.sample(5)
ipl.sample(5)

In [ ]:
"""info() : the most powerfull function. it give us to much information about data. it gives the following information:
memory size
counts of missing in columns
datatype of each columns
summary of dtypes of row -->  dtypes: float64(1), int64(3), object(14)
about index : RangeIndex: 1629 entries, 0 to 1628
about columns : Data columns (total 18 columns):
"""
movies.info()

In [ ]:
ipl.info()

In [ ]:
"describe(): this is also most important function: it gives us the mathemathical summary of numerical columns of the dataset."
movies.describe()

In [ ]:
ipl.describe()

In [ ]:
"isnull(): it is used for checking wether our data contain null values: it would check columns "
ipl.isnull()
ipl.isna()

In [ ]:
movies.isnull().sum()

In [ ]:
movies.isnull().sum()

In [ ]:
"Note: isnull() and isna() both are same just the isnull() is the second alias and prefrence should be isna() it is used more by enginners."

In [71]:
"duplicated(): it gives us if there is any duplicated row in the dataset or not."
movies.duplicated().sum()

np.int64(0)

In [75]:
ipl.duplicated().sum()
data

    IQ  Marks  package
0  100     80       10
1  120    100       14
2   90     70        5
3   70     60        4

In [82]:
data.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [ ]:
"rename(): through this function we can rename our column name. this is usefull function."
data

    IQ  Marks  package
0  100     80       10
1  120    100       14
2   90     70        5
3   70     60        4
4   70     60        4

In [90]:
data.rename(columns={"Marks":"Percent","package":"LPA"},inplace=True) 
data

    IQ  Percent  LPA
0  100       80   10
1  120      100   14
2   90       70    5
3   70       60    4
4   70       60    4