In [47]:
import pandas as pd
import numpy as np

In [48]:
movies = pd.read_csv("imdb-top-1000.csv")
# delivers = pd.read_csv("deliveries.csv")

In [49]:
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

groupby object:

In this lecture we will study groupby object.

In [50]:
geners = movies.groupby("Genre")
geners.sum()
geners.min()
geners.max()
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [51]:
movies.groupby("Genre").sum()["Gross"].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [52]:
movies.groupby("Genre")["Gross"].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [53]:
movies.groupby("Genre")["IMDB_Rating"].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [54]:
movies.groupby("Director")["No_of_Votes"].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [55]:
# movies["Director"].value_counts().sort_values(ascending=False)
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [56]:
movies.groupby("Genre")["IMDB_Rating"].max().sort_values(ascending=False)

Genre
Drama        9.3
Crime        9.2
Action       9.0
Biography    8.9
Western      8.8
Adventure    8.6
Comedy       8.6
Animation    8.6
Horror       8.5
Mystery      8.4
Fantasy      8.1
Film-Noir    8.1
Family       7.8
Thriller     7.8
Name: IMDB_Rating, dtype: float64

In [57]:
movies.groupby("Star1")["Series_Title"].count().sort_values(ascending=False)

Star1
Tom Hanks               12
Robert De Niro          11
Clint Eastwood          10
Al Pacino               10
Humphrey Bogart          9
                        ..
Zbigniew Zamachowski     1
Zooey Deschanel          1
Çetin Tekindor           1
Éric Toledano            1
Aaron Taylor-Johnson     1
Name: Series_Title, Length: 660, dtype: int64

In [58]:
len(movies.groupby("Genre"))

14

In [59]:
movies["Genre"].nunique()

14

In [60]:
movies.groupby("Genre").size().sort_values(ascending=False)

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Family         2
Fantasy        2
Thriller       1
dtype: int64

In [61]:
movies["Genre"].value_counts()

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

In [62]:
geners = movies.groupby("Genre")
geners.first()
geners.get_group("Action")
geners.groups
geners.last()
geners.nth(4) # getting any movie of the each group.

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
20,Soorarai Pottru,2020,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648.0,NaN
22,Cidade de Deus,2002,130,Crime,8.6,Fernando Meirelles,Kátia Lund,699256,7563397.0,79.0
38,The Pianist,2002,150,Biography,8.5,Roman Polanski,Adrien Brody,729603,32572577.0,85.0
58,Spider-Man: Into the Spider-Verse,2018,117,Animation,8.4,Bob Persichetti,Peter Ramsey,375110,190241310.0,87.0
64,3 Idiots,2009,170,Comedy,8.4,Rajkumar Hirani,Aamir Khan,344445,6532908.0,67.0
114,2001: A Space Odyssey,1968,149,Adventure,8.3,Stanley Kubrick,Keir Dullea,603517,56954992.0,84.0
220,Kahaani,2012,122,Mystery,8.1,Sujoy Ghosh,Vidya Balan,57806,1035953.0,NaN
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0

In [63]:
geners.get_group("Action")
movies[movies["Genre"] == "Action"]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
...,...,...,...,...,...,...,...,...,...,...
968,Falling Down,1993,113,Action,7.6,Joel Schumacher,Michael Douglas,171640,40903593.0,56.0
979,Lethal Weapon,1987,109,Action,7.6,Richard Donner,Mel Gibson,236894,65207127.0,68.0
982,Mad Max 2,1981,96,Action,7.6,George Miller,Mel Gibson,166588,12465371.0,77.0
983,The Warriors,1979,92,Action,7.6,Walter Hill,Michael Beck,93878,22490039.0,65.0
985,Escape from Alcatraz,1979,112,Action,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0

In [64]:
geners.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [65]:
geners.sample()
geners.sample(2,replace=True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
72,Raiders of the Lost Ark,1981,115,Action,8.4,Steven Spielberg,Harrison Ford,884112,248159971.0,85.0
821,The Last of the Mohicans,1992,112,Action,7.7,Michael Mann,Daniel Day-Lewis,150409,75505856.0,76.0
226,Harry Potter and the Deathly Hallows: Part 2,2011,130,Adventure,8.1,David Yates,Daniel Radcliffe,764493,381011219.0,85.0
470,Hunt for the Wilderpeople,2016,101,Adventure,7.9,Taika Waititi,Sam Neill,111483,5202582.0,81.0
245,"Monsters, Inc.",2001,92,Animation,8.1,Pete Docter,David Silverman,815505,289916256.0,79.0
401,Beauty and the Beast,1991,84,Animation,8.0,Gary Trousdale,Kirk Wise,417178,218967620.0,95.0
622,American Gangster,2007,157,Biography,7.8,Ridley Scott,Denzel Washington,392449,130164645.0,76.0
810,Shine,1996,105,Biography,7.7,Scott Hicks,Geoffrey Rush,51350,35811509.0,87.0
250,The Truman Show,1998,103,Comedy,8.1,Peter Weir,Jim Carrey,939631,125618201.0,90.0
667,Night on Earth,1991,129,Comedy,7.8,Jim Jarmusch,Winona Ryder,55362,2015810.0,68.0
299,Les quatre cents coups,1959,99,Crime,8.1,François Truffaut,Jean-Pierre Léaud,105291,263473309.0,NaN
556,Strangers on a Train,1951,101,Crime,7.9,Alfred Hitchcock,Farley Granger,123341,7630000.0,88.0
881,The Florida Project,2017,111,Drama,7.6,Sean Baker,Brooklynn Prince,95181,5904366.0,92.0
310,The Red Shoes,1948,135,Drama,8.1,Michael Powell,Emeric Pressburger,30935,10900000.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
145,Shutter Island,2010,138,Mystery,8.2,Martin Scorsese,Leonardo DiCaprio,1129894,128012934.0,63.0
899,El cuerpo,2012,112,Mystery,7.6,Oriol Paulo,Jose Coronado,57549,140340673.0,NaN
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
691,The Outlaw Josey Wales,1976,135,Western,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0

In [66]:
geners.nunique()
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [67]:
"appliying dictionary"
geners.agg(
    {
        "Runtime": "sum",
        "IMDB_Rating": "mean",
        "No_of_Votes": "sum",
        "Gross": "sum",
        "Metascore":"min"
        }
    )

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196     7.949419     72282412  3.263226e+10       33.0
Adventure     9656     7.937500     22576163  9.496922e+09       41.0
Animation     8166     7.930488     21978630  1.463147e+10       61.0
Biography    11970     7.938636     24006844  8.276358e+09       48.0
Comedy       17380     7.901290     27620327  1.566387e+10       45.0
Crime        13524     8.016822     33533615  8.452632e+09       47.0
Drama        36049     7.957439     61367304  3.540997e+10       28.0
Family         215     7.800000       551221  4.391106e+08       67.0
Fantasy        170     8.000000       146222  7.827267e+08        NaN
Film-Noir      312     7.966667       367215  1.259105e+08       94.0
Horror        1123     7.909091      3742556  1.034649e+09       46.0
Mystery       1429     7.975000      4203004  1.256417e+09       52.0
Thriller       108     7.800000        27733  1.755074e+07       81.0
Western        593     8.350000      1289665  5.822151e+07       69.0

In [68]:
"through list:"
geners.agg(["sum","max","min"])

                                                Series_Title  \
                                                         sum
Genre
Action     The Dark KnightThe Lord of the Rings: The Retu...
Adventure  InterstellarBack to the FutureInglourious Bast...
Animation  Sen to Chihiro no kamikakushiThe Lion KingHota...
Biography  Schindler's ListGoodfellasHamiltonThe Intoucha...
Comedy     GisaengchungLa vita è bellaModern TimesCity Li...
Crime      The GodfatherThe Godfather: Part II12 Angry Me...
Drama      The Shawshank RedemptionFight ClubForrest Gump...
Family     E.T. the Extra-TerrestrialWilly Wonka & the Ch...
Fantasy                Das Cabinet des Dr. CaligariNosferatu
Film-Noir   The Third ManThe Maltese FalconShadow of a Doubt
Horror     PsychoAlienThe ThingThe ExorcistNight of the L...
Mystery    MementoRear WindowVertigoShutter IslandKahaani...
Thriller                                     Wait Until Dark
Western    Il buono, il brutto, il cattivoOnce Upon a Tim...

                                                \
                                           max
Genre
Action                                 Yôjinbô
Adventure                           Zombieland
Animation          Ôkami kodomo no Ame to Yuki
Biography                              Zerkalo
Comedy                Zindagi Na Milegi Dobara
Crime                        À bout de souffle
Drama                                Zwartboek
Family     Willy Wonka & the Chocolate Factory
Fantasy                              Nosferatu
Film-Noir                        The Third Man
Horror                               The Thing
Mystery                                Vertigo
Thriller                       Wait Until Dark
Western                 The Outlaw Josey Wales

                                            \
                                       min
Genre
Action                                 300
Adventure            2001: A Space Odyssey
Animation                            Akira
Biography                 12 Years a Slave
Comedy                (500) Days of Summer
Crime                         12 Angry Men
Drama                                 1917
Family          E.T. the Extra-Terrestrial
Fantasy       Das Cabinet des Dr. Caligari
Film-Noir                Shadow of a Doubt
Horror                               Alien
Mystery                          Dark City
Thriller                   Wait Until Dark
Western    Il buono, il brutto, il cattivo

                                               Released_Year              \
                                                         sum   max   min
Genre
Action     2008200320102001200219991980197719621954200019...  2019  1924
Adventure  2014198520091981196819621959201319751963194819...    PG  1925
Animation  2001199419882016201820172008199719952019200920...  2020  1940
Biography  1993199020202011200220171995198420182013201320...  2020  1928
Comedy     2019199719361931200919641940200120001973196019...  2020  1921
Crime      1972197419571994200219991995199120192006199519...  2019  1931
Drama      1994199919941975202019981946201420061998198819...  2020  1925
Family                                              19821971  1982  1971
Fantasy                                             19201922  1922  1920
Film-Noir                                       194919411943  1949  1941
Horror          19601979198219731968196120171978193320042001  2017  1933
Mystery     200019541958201020121995197219381988201219981997  2012  1938
Thriller                                                1967  1967  1967
Western                                     1966196819651976  1976  1965

          Runtime           IMDB_Rating  ...                     Star1  \
              sum  max  min         sum  ...                       min
Genre                                    ...
Action      22196  321   45      1367.3  ...                Aamir Khan
Adventure    9656  228   88       571.5  ...                Aamir Khan
Animation    8166  137   71       650.3  ...             Adrian Molina
Biography   11970  209   93       698.6  ...              Adrien Brody
Comedy      17380  188   68      1224.7  ...                Aamir Khan
Crime       13524  229   80       857.8  ...                Ajay Devgn
Drama       36049  242   64      2299.7  ...                Abhay Deol
Family        215  115  100        15.6  ...               Gene Wilder
Fantasy       170   94   76        16.0  ...               Max Schreck
Film-Noir     312  108  100        23.9  ...           Humphrey Bogart
Horror       1123  122   71        87.0  ...           Anthony Perkins
Mystery      1429  138   96        95.7  ...  Bernard-Pierre Donnadieu
Thriller      108  108  108         7.8  ...            Audrey Hepburn
Western       593  165  132        33.4  ...            Clint Eastwood

          No_of_Votes                          Gross               \
                  sum      max     min           sum          max
Genre
Action       72282412  2303232   25312  3.263226e+10  936662225.0
Adventure    22576163  1512360   29999  9.496922e+09  874211619.0
Animation    21978630   999790   25229  1.463147e+10  873839108.0
Biography    24006844  1213505   27254  8.276358e+09  753585104.0
Comedy       27620327   939631   26337  1.566387e+10  886752933.0
Crime        33533615  1826188   27712  8.452632e+09  790482117.0
Drama        61367304  2343110   25088  3.540997e+10  924558264.0
Family         551221   372490  178731  4.391106e+08  435110554.0
Fantasy        146222    88794   57428  7.827267e+08  445151978.0
Film-Noir      367215   158731   59556  1.259105e+08  123353292.0
Horror        3742556   787806   27007  1.034649e+09  298791505.0
Mystery       4203004  1129894   33982  1.256417e+09  474203697.0
Thriller        27733    27733   27733  1.755074e+07   17550741.0
Western       1289665   688390   65659  5.822151e+07   31800000.0

                       Metascore
                   min       sum    max   min
Genre
Action          3296.0   10499.0   98.0  33.0
Adventure      61001.0    5020.0  100.0  41.0
Animation     128985.0    6082.0   96.0  61.0
Biography      21877.0    6023.0   97.0  48.0
Comedy          1305.0    9840.0   99.0  45.0
Crime           6013.0    6706.0  100.0  47.0
Drama           3600.0   19208.0  100.0  28.0
Family       4000000.0     158.0   91.0  67.0
Fantasy    337574718.0       0.0    NaN   NaN
Film-Noir     449191.0     287.0   97.0  94.0
Horror         89029.0     880.0   97.0  46.0
Mystery      1035953.0     633.0  100.0  52.0
Thriller    17550741.0      81.0   81.0  81.0
Western      5321508.0     313.0   90.0  69.0

[14 rows x 27 columns]

In [69]:
"applying both syntax in one "
geners.agg(
    {
        "Runtime": ["min","max"],
        "IMDB_Rating": "mean",
        "No_of_Votes": ["sum","max"],
        "Gross": "sum",
        "Metascore":"min"
        }
    )

          Runtime      IMDB_Rating No_of_Votes                  Gross  \
              min  max        mean         sum      max           sum
Genre
Action         45  321    7.949419    72282412  2303232  3.263226e+10
Adventure      88  228    7.937500    22576163  1512360  9.496922e+09
Animation      71  137    7.930488    21978630   999790  1.463147e+10
Biography      93  209    7.938636    24006844  1213505  8.276358e+09
Comedy         68  188    7.901290    27620327   939631  1.566387e+10
Crime          80  229    8.016822    33533615  1826188  8.452632e+09
Drama          64  242    7.957439    61367304  2343110  3.540997e+10
Family        100  115    7.800000      551221   372490  4.391106e+08
Fantasy        76   94    8.000000      146222    88794  7.827267e+08
Film-Noir     100  108    7.966667      367215   158731  1.259105e+08
Horror         71  122    7.909091     3742556   787806  1.034649e+09
Mystery        96  138    7.975000     4203004  1129894  1.256417e+09
Thriller      108  108    7.800000       27733    27733  1.755074e+07
Western       132  165    8.350000     1289665   688390  5.822151e+07

          Metascore
                min
Genre
Action         33.0
Adventure      41.0
Animation      61.0
Biography      48.0
Comedy         45.0
Crime          47.0
Drama          28.0
Family         67.0
Fantasy         NaN
Film-Noir      94.0
Horror         46.0
Mystery        52.0
Thriller       81.0
Western        69.0

In [70]:
"looping through groupby"
df = pd.DataFrame(columns=movies.columns)

for group, data in geners:
    df = pd.concat([df, data[data["IMDB_Rating"] == data["IMDB_Rating"].max()]])

df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [71]:
def foo(group):
    return group["Series_Title"].str.startswith("A").sum()

In [72]:
geners.apply(foo)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [73]:
def rank_move(group):
    group["move_rank"] = group["IMDB_Rating"].rank(ascending=False)
    return group

In [74]:
geners.apply(rank_move)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  move_rank
Genre
Action   2        2303232  534858444.0       84.0        1.0
         5        1642758  377845905.0       94.0        2.0
         8        2067042  292576195.0       74.0        3.5
         10       1661481  315544750.0       92.0        3.5
         13       1485555  342551365.0       87.0        6.0
...                   ...          ...        ...        ...
Thriller 700        27733   17550741.0       81.0        1.0
Western  12        688390    6100000.0       90.0        1.0
         48        302844    5321508.0       80.0        2.0
         115       232772   15000000.0       74.0        3.0
         691        65659   31800000.0       69.0        4.0

[1000 rows x 10 columns]

In [75]:
def normal(group):
    group["normalize"] = (group["IMDB_Rating"] - group["IMDB_Rating"].min()) / (group["IMDB_Rating"].max() - group["IMDB_Rating"].min())
    return group

In [76]:
geners.apply(normal)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  normalize
Genre
Action   2        2303232  534858444.0       84.0   1.000000
         5        1642758  377845905.0       94.0   0.928571
         8        2067042  292576195.0       74.0   0.857143
         10       1661481  315544750.0       92.0   0.857143
         13       1485555  342551365.0       87.0   0.785714
...                   ...          ...        ...        ...
Thriller 700        27733   17550741.0       81.0        NaN
Western  12        688390    6100000.0       90.0   1.000000
         48        302844    5321508.0       80.0   0.700000
         115       232772   15000000.0       74.0   0.500000
         691        65659   31800000.0       69.0   0.000000

[1000 rows x 10 columns]

In [77]:
duo = movies.groupby(["Director","Star1"])

In [78]:
duo.size()

Director             Star1
Aamir Khan           Amole Gupte       1
Aaron Sorkin         Eddie Redmayne    1
Abdellatif Kechiche  Léa Seydoux       1
Abhishek Chaubey     Shahid Kapoor     1
Abhishek Kapoor      Amit Sadh         1
                                      ..
Zaza Urushadze       Lembit Ulfsak     1
Zoya Akhtar          Hrithik Roshan    1
                     Vijay Varma       1
Çagan Irmak          Çetin Tekindor    1
Ömer Faruk Sorak     Cem Yilmaz        1
Length: 898, dtype: int64

In [79]:
duo.get_group(("Aamir Khan", "Amole Gupte"))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN

In [80]:
duo["Gross"].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [81]:
"Find the best in (term of meta score (avg)) actor -> genre combo"
movies.groupby(["Star1","Genre"])["Metascore"].mean().reset_index().sort_values("Metascore", ascending=False).head(1)

             Star1      Genre  Metascore
606  Peter O'Toole  Adventure      100.0

In [82]:
duo.agg(["min","max"])

                                                  Series_Title  \
                                                           min
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab
Abhishek Kapoor     Amit Sadh                      Kai po che!
...                                                        ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara
                    Vijay Varma                      Gully Boy
Çagan Irmak         Çetin Tekindor              Babam ve Oglum
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.

                                                               Released_Year  \
                                                           max           min
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par          2007
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7          2020
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle          2013
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab          2016
Abhishek Kapoor     Amit Sadh                      Kai po che!          2013
...                                                        ...           ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid          2013
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara          2011
                    Vijay Varma                      Gully Boy          2019
Çagan Irmak         Çetin Tekindor              Babam ve Oglum          2005
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.          2004

                                         Runtime           Genre             \
                                     max     min  max        min        max
Director            Star1
Aamir Khan          Amole Gupte     2007     165  165      Drama      Drama
Aaron Sorkin        Eddie Redmayne  2020     129  129      Drama      Drama
Abdellatif Kechiche Léa Seydoux     2013     180  180      Drama      Drama
Abhishek Chaubey    Shahid Kapoor   2016     148  148     Action     Action
Abhishek Kapoor     Amit Sadh       2013     130  130      Drama      Drama
...                                  ...     ...  ...        ...        ...
Zaza Urushadze      Lembit Ulfsak   2013      87   87      Drama      Drama
Zoya Akhtar         Hrithik Roshan  2011     155  155     Comedy     Comedy
                    Vijay Varma     2019     154  154      Drama      Drama
Çagan Irmak         Çetin Tekindor  2005     112  112      Drama      Drama
Ömer Faruk Sorak    Cem Yilmaz      2004     127  127  Adventure  Adventure

                                   IMDB_Rating      No_of_Votes          \
                                           min  max         min     max
Director            Star1
Aamir Khan          Amole Gupte            8.4  8.4      168895  168895
Aaron Sorkin        Eddie Redmayne         7.8  7.8       89896   89896
Abdellatif Kechiche Léa Seydoux            7.7  7.7      138741  138741
Abhishek Chaubey    Shahid Kapoor          7.8  7.8       27175   27175
Abhishek Kapoor     Amit Sadh              7.7  7.7       32628   32628
...                                        ...  ...         ...     ...
Zaza Urushadze      Lembit Ulfsak          8.2  8.2       40382   40382
Zoya Akhtar         Hrithik Roshan         8.1  8.1       67927   67927
                    Vijay Varma            8.0  8.0       31886   31886
Çagan Irmak         Çetin Tekindor         8.3  8.3       78925   78925
Ömer Faruk Sorak    Cem Yilmaz             8.0  8.0       56960   56960

                                          Gross              Metascore
                                            min          max       min   max
Director            Star1
Aamir Khan          Amole Gupte       1223869.0    1223869.0       NaN   NaN
Aaron Sorkin        Eddie Redmayne  853090410.0  853090410.0      77.0  77.0
Abdellatif Kechiche Léa Seydoux       2199675.0    2199675.0      89.0  89.0
Abhishek Chaubey    Shahid Kapoor   218428303.0  218428303.0       NaN   NaN
Abhishek Kapoor     Amit Sadh         1122527.0    1122527.0      40.0  40.0
...                                         ...          ...       ...   ...
Zaza Urushadze      Lembit Ulfsak      144501.0     144501.0      73.0  73.0
Zoya Akhtar         Hrithik Roshan    3108485.0    3108485.0       NaN   NaN
                    Vijay Varma       5566534.0    5566534.0      65.0  65.0
Çagan Irmak         Çetin Tekindor  461855363.0  461855363.0       NaN   NaN
Ömer Faruk Sorak    Cem Yilmaz      196206077.0  196206077.0       NaN   NaN

[898 rows x 16 columns]

In [83]:
ipl = pd.read_csv("deliveries.csv")

In [84]:
ipl

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [85]:
ipl.shape

(179078, 21)

In [86]:
objects = ipl.groupby("batsman")["total_runs"].sum().sort_values(ascending=False).head(1)
objects

batsman
SK Raina    5651
Name: total_runs, dtype: int64

In [87]:
highest_runs = ipl.groupby("batsman")["batsman_runs"].sum().sort_values(ascending=False).head(1)
highest_runs

batsman
V Kohli    5434
Name: batsman_runs, dtype: int64

In [88]:
six = ipl[ipl["batsman_runs"] == 6]

In [89]:
six.groupby("batsman")["batsman"].count().sort_values(ascending=False).head(1).index[0]
six

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
47,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,4,MC Henriques,S Dhawan,TM Head,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
75,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,13,2,Yuvraj Singh,MC Henriques,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
89,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,3,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
91,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,5,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178987,11415,2,Chennai Super Kings,Mumbai Indians,6,4,SR Watson,SK Raina,SL Malinga,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179048,11415,2,Chennai Super Kings,Mumbai Indians,16,1,DJ Bravo,SR Watson,SL Malinga,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179061,11415,2,Chennai Super Kings,Mumbai Indians,18,2,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179062,11415,2,Chennai Super Kings,Mumbai Indians,18,3,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179063,11415,2,Chennai Super Kings,Mumbai Indians,18,4,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

In [90]:
temp_df = ipl[ipl["over"] > 15]
temp_df = temp_df[(temp_df["batsman_runs"] == 4) | (temp_df["batsman_runs"] == 6)]
temp_df.groupby("batsman")["batsman"].count().sort_values(ascending=False).head(1).index[0]

'MS Dhoni'

In [101]:
temp_df = ipl[ipl["batsman"] == "V Kohli"]
temp_df.groupby("bowling_team")["batsman_runs"].sum().reset_index()

               bowling_team  batsman_runs
0       Chennai Super Kings           749
1           Deccan Chargers           306
2            Delhi Capitals            66
3          Delhi Daredevils           763
4             Gujarat Lions           283
5           Kings XI Punjab           636
6      Kochi Tuskers Kerala            50
7     Kolkata Knight Riders           675
8            Mumbai Indians           628
9             Pune Warriors           128
10         Rajasthan Royals           370
11   Rising Pune Supergiant            83
12  Rising Pune Supergiants           188
13      Sunrisers Hyderabad           509

In [114]:
def highest(batsman):
    temp_df = ipl[ipl["batsman"] == batsman]
    return temp_df.groupby("match_id")["batsman_runs"].sum().sort_values(ascending=False).head(1).values[0]

In [115]:
highest("DA Warner")

np.int64(126)