In [ ]:
import pandas as pd
import numpy as np

In [ ]:
titanic = pd.read_csv("Titanic-Dataset.csv")

In [ ]:
"""1) Basic Level

These are for getting comfortable with the DataFrame structure and core pandas methods.

Load the CSV file into a pandas DataFrame.
Display the first 5 rows of the dataset.
Display the last 5 rows of the dataset.
Find the number of rows and columns in the dataset.
Show all column names.
Check the data types of each column.
Get a compact summary of the dataset using info.
Find the total number of missing values in each column.
Count how many passengers are in the dataset.
Find the number of unique values in each column.
Show the basic statistics of numerical columns.
Select only the columns Name, Sex, and Age.
Select all passengers who are female.
Select all passengers whose age is greater than 30.
Count how many passengers survived and how many did not.

What you learn here:
head(), tail(), shape, columns, dtypes, info(), isna(), nunique(), describe(), boolean filtering, value_counts().

2) Intermediate Level

These questions push you into filtering, sorting, grouping, and cleaning.

Find the average age of all passengers.
Find the average fare paid by passengers in each class.
Group passengers by sex and find how many survived in each group.
Group passengers by Pclass and calculate the average survival rate.
Find the number of male and female passengers in the dataset.
Find the youngest and oldest passenger.
Sort the dataset by age in ascending order.
Sort the dataset by fare in descending order.
Find all passengers who traveled with siblings/spouses.
Find all passengers who traveled alone.
Replace missing values in Age with the mean age.
Replace missing values in Embarked with the most frequent value.
Drop the Cabin column and explain why that might be useful.
Create a new column called FamilySize using SibSp + Parch + 1.
Find the average fare for passengers with family size greater than 1.
Find all passengers whose name contains “Mrs”.
Count how many passengers embarked from each port.
Find the survival rate for passengers who embarked from each port.
Compare the average age of survivors and non-survivors.
Find the top 10 passengers who paid the highest fare.

What you learn here:
groupby(), mean(), sum(), count(), sort_values(), fillna(), drop(), string filtering, new column creation, logical conditions.

3) Level Up / Advanced Practice

These are for stronger pandas thinking and real analysis style work.

Create a new column AgeGroup with categories like Child, Teen, Adult, Senior.
Find survival rate by age group.
Find survival rate by gender and passenger class together.
Create a pivot table showing survival count by Sex and Pclass.
Create a pivot table showing average fare by Embarked and Pclass.
Find passengers with missing age values and inspect whether they share common characteristics.
Use loc to select passengers who are female, survived, and traveled in first class.
Use iloc to select the first 10 rows and only the first 5 columns.
Find passengers with ticket numbers appearing more than once.
Check whether shared tickets are linked to higher survival.
Create a new column IsAlone based on family size.
Compare survival rate of passengers traveling alone vs with family.
Find the correlation between numerical features and survival.
Identify outliers in Fare using quantiles or IQR.
Replace missing ages by median age within each Pclass.
Create a cleaned dataset with missing values handled properly.
Make a summary DataFrame showing:
total passengers
survivors
non-survivors
survival rate
average age
average fare
Find the most common passenger title from the Name column.
Extract titles such as Mr, Mrs, Miss from names and analyze survival by title.
Write one complete analysis report based on the dataset using only pandas.

What you learn here:
loc[], iloc[], pivot_table(), feature engineering, grouping on multiple columns, correlation, quantile-based analysis, and cleaning strategies.

4) Challenge Tasks

These are excellent if you want to move toward real project-level pandas use.

Build a full Titanic summary dashboard using only pandas outputs.
Create a survival analysis by Sex, Pclass, and AgeGroup.
Find which combination of Sex and Pclass had the highest survival rate.
Create a custom function to classify passengers as high, medium, or low fare.
Apply your function to create a new fare category column.
Compare survival rates across fare categories.
Find whether passengers with larger families had better or worse survival.
Create a clean final DataFrame ready for machine learning.
Write 5 insights from the dataset using only pandas.
Try to reproduce a mini exploratory data analysis without using any plotting library."""

In [ ]:
first_five_row = titanic.head(5)
first_five_row

In [ ]:
last_five_rows = titanic.tail(5)
last_five_rows

In [ ]:
rows, columns = titanic.shape
print("rows:", rows)
print("columns:", columns)

In [ ]:
columns_names = titanic.columns
columns_names

In [ ]:
compact_summary = titanic.info()
compact_summary

In [ ]:
titanic.isnull().sum()

In [ ]:
titanic["PassengerId"].size
titanic["PassengerId"].count()
len(titanic["PassengerId"])

In [ ]:
titanic.describe()

In [ ]:
titanic.dtypes

In [ ]:
titanic

In [ ]:
titanic[titanic["Sex"] == "female"]

In [ ]:
titanic[titanic["Age"] > 30]

In [ ]:
print("Died:",titanic["Survived"].value_counts()[0])
print("Survived:",titanic["Survived"].value_counts()[1])

In [ ]:
titanic.nunique()

In [ ]:
"Find the average age of all passengers"
np.round(titanic["Age"].mean())

In [ ]:
titanic

In [ ]:
average_fare = titanic["Fare"].mean()
round(average_fare)

In [ ]:
titanic["Sex"].value_counts()

In [ ]:
print(titanic["Age"].max())
print(titanic["Age"].min())

In [ ]:
titanic.sort_values("Age")

In [ ]:
titanic.sort_values("Fare",ascending=False)

In [ ]:
titanic[titanic["SibSp"] > 0]

In [ ]:
titanic[titanic["SibSp"] == 0]

In [ ]:
# titanic["Age"] = titanic["Age"].fillna(titanic["Age"].mean())

In [ ]:
titanic

In [ ]:
titanic["Cabin"].isna().sum()

In [ ]:
titanic.drop(columns=["Cabin"])

In [ ]:
titanic

In [129]:
titanic["FamilySize"] = titanic["SibSp"] + titanic["Parch"] + 1
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1

In [ ]:
titanic

In [130]:
titanic[titanic["FamilySize"] > 1]["Fare"].mean()

np.float64(48.83227542372882)

In [ ]:
def fun(value):
    return value.str.contains("Mrs")

In [140]:
titanic[titanic["Name"].str.contains("Mrs")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,3
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,2
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,3
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C,2
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,2
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,2
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,6

In [142]:
titanic["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [143]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1

In [158]:
print(sum(titanic["Survived"] == 0)/len(titanic["Survived"]==0))
print(sum(titanic["Survived"] == 1)/len(titanic["Survived"]==1))

0.6161616161616161
0.3838383838383838

In [161]:
titanic["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [166]:
titanic["Fare"].sort_values(ascending=False).head(10)

679    512.3292
258    512.3292
737    512.3292
88     263.0000
438    263.0000
341    263.0000
27     263.0000
742    262.3750
311    262.3750
299    247.5208
Name: Fare, dtype: float64

In [170]:
def categering(value):
    if value < 12:
        return "child"
    elif 12 <= value < 18:
        return "Teen"
    elif 18 <= value < 40:
        return "Adult"
    else:
        return "Senior"

titanic["AgeGroup"] = titanic["Age"].apply(categering)
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4,Senior
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,Adult

In [176]:
def survivel_rate_age_group():
    titanic_survivers = titanic["Survived"].value_counts()
    series = titanic["AgeGroup"].value_counts()
    for age_group in series.index:
        rate = series[age_group] / titanic_survivers[1]
        print(f"{age_group}: {rate:.2%}")

survivel_rate_age_group()

Adult: 128.07%
Senior: 99.42%
child: 19.88%
Teen: 13.16%

In [175]:
titanic["AgeGroup"].value_counts()

AgeGroup
Adult     438
Senior    340
child      68
Teen       45
Name: count, dtype: int64

In [186]:
titanic["Alone"] = titanic["FamilySize"].apply(lambda x: "alone" if x == 1 else "Not alone")

In [187]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,AgeGroup,Alone
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,Adult,Not alone
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,Adult,Not alone
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,Adult,alone
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,Adult,Not alone
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,Adult,alone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,Adult,alone
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,Adult,alone
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4,Senior,Not alone
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,Adult,alone
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,Adult,alone

In [198]:
total_passenger = titanic["PassengerId"].count()
survivors = titanic["Survived"].value_counts()[1]
non_survivors = titanic["Survived"].value_counts()[0]
non_survivors
survival_rate = titanic["Survived"].value_counts()[1]/len(titanic["Survived"])
average_age = titanic["Age"].mean()
average_fare = titanic["Age"].mean()
data = [total_passenger,survivors,non_survivors,survival_rate,average_age,average_fare]
summary_data = pd.DataFrame(data,index=["total_passenger","survivors","non_survivors","survival_rate","average_age","average_fare"])
summary_data

                          0
total_passenger  891.000000
survivors        342.000000
non_survivors    549.000000
survival_rate      0.383838
average_age       29.699118
average_fare      29.699118

In [199]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,AgeGroup,Alone
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,Adult,Not alone
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,Adult,Not alone
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,Adult,alone
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,Adult,Not alone
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,Adult,alone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,Adult,alone
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,Adult,alone
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4,Senior,Not alone
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,Adult,alone
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,Adult,alone